ARG ELIXIR_VERSION=1.19.5
ARG OTP_VERSION=28.3.1
ARG DEBIAN_VERSION=trixie-20260202-slim
ARG BASE_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BASE_IMAGE} AS base

RUN apt-get update -y && \
    apt-get install -y build-essential curl git inotify-tools procps

RUN curl -fsSL https://deb.nodesource.com/setup_24.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -yqq nodejs && \
    npm install -g npm

FROM base AS local

RUN mkdir -p /workspaces/${PROJECT_DIR}/assets/node_modules \
             /workspaces/${PROJECT_DIR}/_build \
             /workspaces/${PROJECT_DIR}/deps

RUN curl -sL -o \
      /usr/local/bin/tidewave \
      https://github.com/tidewave-ai/tidewave_app/releases/latest/download/tidewave-cli-$(uname -m)-unknown-linux-gnu && \
    chmod +x /usr/local/bin/tidewave

RUN mix local.hex --force && \
    mix local.rebar --force

RUN --mount=type=secret,id=OBAN_LICENSE_KEY,mode=0444 \
    mix hex.repo add oban https://repo.oban.pro \
      --fetch-public-key SHA256:4/OSKi0NRF91QVVXlGAhb/BIMLnK8NHcx/EWs+aIWPc \
      --auth-key "$(cat /run/secrets/OBAN_LICENSE_KEY)"

ENV ERL_AFLAGS="-kernel shell_history enabled"
WORKDIR /workspaces/${PROJECT_DIR}
